battlestar_github/battlestar_github/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^repotracker/', include('repotracker.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

battlestar_github/repotracker/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<repocomp_id>[0-9]+)/results/$', views.results, name='results'),
]

battlestar_github/repotracker/models.py
from django.db import models


class Repo(models.Model):
    repo_url = models.CharField(max_length=200)

    def __str__(self):              # __unicode__ on Python 2
        return self.repo_url


class RepoComp(models.Model):
    repo1_url = models.CharField(max_length=200)
    repo1_star_ct = models.IntegerField(default=0)
    repo1_watch_ct = models.IntegerField(default=0)
    repo1_fork_ct = models.IntegerField(default=0)

    repo2_url = models.CharField(max_length=200)
    repo2_star_ct = models.IntegerField(default=0)
    repo2_watch_ct = models.IntegerField(default=0)
    repo2_fork_ct = models.IntegerField(default=0)

    def __str__(self):              # __unicode__ on Python 2
      return self.repo2_url

battlestar_github/repotracker/forms.py
from django.forms import ModelForm, TextInput
from .models import RepoComp

class RepoForm(ModelForm):
    class Meta:
    	model = RepoComp
    	fields = ['repo1_url','repo2_url']
      #widgets = {
      #    'name': TextInput(attrs={'placeholder':'[USER]/[REPOSITORY]'}),
      #}

battlestar_github/repotracker/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.views import generic
from django.template import RequestContext, loader

from .models import RepoComp
from .forms import RepoForm


def index(request, pk=None):
  if request.method == 'POST':
      form = RepoForm(request.POST)
      if form.is_valid():
      	  #form.cleaned_data['repo1_url'] #TODO: validate the input we're getting on the repo urls
          #form.cleaned_data['repo2_url'] #TODO: validate the input we're getting on the repo urls
          # process the data in form.cleaned_data as required
          # ...
          repocomp = form.save()
          return HttpResponseRedirect(reverse('results', args=(repocomp.id,)))

  else:
      form = RepoForm()

  return render(request, 'repotracker/index.html', {'form': form})


def results(request, repocomp_id):
    repocomp = get_object_or_404(RepoComp, pk=repocomp_id)
    return render(request, 'repotracker/results.html', {'repocomp': repocomp})

battlestar_github/repotracker/templates/repotracker/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'repotracker/css/style.css' %}" />

<h1>Battle of the GitHub Stars</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="" method="post">
{% csrf_token %}
<div class="input-group">
	<div class="">      
      <h3>Github Repo 1 url:</h3>
      <label for="{{form.repo1_url.id_for_label}}">https://github.com/</label>
      {{form.repo1_url}}
      <p class="instr_sub">eg, [USER]/[REPOSITORY]<p>
      {{ form.repo1_url.errors }}
  </div>
  <p>~vs.~</p>
  <div class="">
      <h3>Github Repo 2 url:</h3>
      <label for="{{form.repo2_url.id_for_label}}">https://github.com/</label>
      {{form.repo2_url}}
      <p class="instr_sub">eg, [USER]/[REPOSITORY]<p>
      {{ form.repo2_url.errors }}
  </div>
</div>
<br>
<input type="submit" value="Compare Stats" />
</form>

battlestar_github/repotracker/templates/repotracker/results.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'repotracker/css/style.css' %}" />
<script src="{% static "repotracker/js/vendor/jquery.min.js" %}" type="text/javascript"></script>
<script src="{% static "repotracker/js/main.js" %}" type="text/javascript"></script>

<script type="text/javascript">
  var repoURLs = ["{{repocomp.repo1_url | safe}}", "{{repocomp.repo2_url | safe}}"];
  
</script>

<h1>Battle of the GitHub Stars: <i>Results!</i></h1>
<h3 id="Announcement"></h3>
<div id="ResultsCnt">
  <div id="id_repo1" class="stats_cnt">
      <h3>Github Repo 1 url:</h3>
      <h4><a href="https://github.com/{{ repocomp.repo1_url }}">https://github.com/{{ repocomp.repo1_url }}</a></h4>
      <p>with:</p>
      <ul class="repo_stats">
        <li id="id_repo1_star_ct">*star_ct* star{{ repocomp.repo1_star_ct|pluralize }}</li>
        <li id="id_repo1_watch_ct">*watch_ct* watcher{{ repocomp.repo1_watch_ct|pluralize }}</li>
        <li id="id_repo1_fork_ct">*fork_ct* fork{{ repocomp.repo1_fork_ct|pluralize }}</li>
      </ul>
      
  </div>
  <p>~vs.~</p>
  <div id="id_repo2" class="stats_cnt">
      <h3>Github Repo 2:</h3>
      <h4><a href="https://github.com/{{ repocomp.repo1_url }}">https://github.com/{{ repocomp.repo2_url }}</a></h4>
      <p>with:</p>
      <ul class="repo_stats">
        <li id="id_repo2_star_ct">*star_ct* star{{ repocomp.repo2_star_ct|pluralize }}</li>
        <li id="id_repo2_watch_ct">*watch_ct* watcher{{ repocomp.repo2_watch_ct|pluralize }}</li>
        <li id="id_repo2_fork_ct">*fork_ct* fork{{ repocomp.repo2_fork_ct|pluralize }}</li>
      </ul>
      
  </div>
</div>